services:
    laravel:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: laravel
        volumes:
            - ./laravel:/var/www/html
            - ./resources/js:/var/www/html/resources/js
        ports:
            - "8000:8000"
        depends_on:
            - mysql
        networks:
            - larareact

    react:
        build:
            context: .
            dockerfile: docker/node/Dockerfile
        container_name: react
        volumes:
            - .:/app
        ports:
            - "5173:5173"
        networks:
            - larareact

    mysql:
        image: mysql:latest
        container_name: db
        restart: unless-stopped
        tty: true
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: valoracion-cursos
            MYSQL_USER: lumagc
            MYSQL_PASSWORD: tusito
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - larareact

    nginx:
        image: nginx:alpine
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - .:/var/www
        ports:
            - "80:80"
        depends_on:
            - laravel
            - react
            - mysql
        networks:
            - larareact
volumes:
    dbdata:
networks:
    larareact:
        driver: bridge